[env:edge_control]
platform = arduino
board = arduino_edge_control
framework = arduino
lib_deps =
    arduino-libraries/Arduino_EdgeControl
    PaulStoffregen/OneWire
    milesburton/DallasTemperature
    bblanchon/ArduinoJson
monitor_speed = 115200
build_flags =
    -DDEBUG_SERIAL=1
    -DFIRMWARE_VERSION='"1.0.0"'
